### ISSUE TITLE
Issue in JSON Config

### ISSUE THREAD

**Issue by SubhashMahato** [VinnyDyn/ActionButtons#1]
Hi @VinnyDyn 

I really liked your PCF control I tried using this as it suits perfectly for one of my requirements. but I am stuck while adding "JSONConfig" in field properties. It is not taking all the JSON configurations as you have mentioned. Is there any other way which you have used. 
Actual JSON
`[
    {
        "ActionUniqueName":"vnb_task_all_attributes",
        "Tooltip":"All Attributes Sample",
        "WebResourceImage":"/WebResources/vnb_all_atributes"
    },
    {
        "ActionUniqueName":"vnb_task_edit",
        "Tooltip":"Edit",
        "WebResourceImage":"/WebResources/vnb_edit"
    },
    {
        "ActionUniqueName":"vnb_task_done",
        "Tooltip":"Done",
        "WebResourceImage":"/WebResources/vnb_done"
    },
    {
        "ActionUniqueName":"vnb_task_cancel",
        "Tooltip":"Cancel",
        "WebResourceImage":"/WebResources/vnb_cancel"
    }
]`

but is is taking only 
`[
    {
        "ActionUniqueName":"vnb_task_all_attributes",
        "Tooltip":"All Attributes Samp`

**Comment by VinnyDyn** [comment]
Hello @SubhashMahato , sorry for the delay.

I tried to solve this problem using the Multiple type instead of SingleLine.TextArea, but the problem persists.

I analyzed the HTML of the DOM on the control's configuration page and changed the 'maxLength' property from 100 to 10000.

That is an workaround solution. I will try to talk to the Microsoft product team to resolve this issue.

Thank you by feedback.

![image](https://user-images.githubusercontent.com/36446614/79070902-ec5ea200-7cae-11ea-8109-5851c1134b21.png)
